"""medication_changes.photo_path

Revision ID: 636c8194274e
Revises: 9ba29a1e5c3e
Create Date: 2026-06-22 14:35:11.741483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636c8194274e'
down_revision: Union[str, Sequence[str], None] = '9ba29a1e5c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_changes', sa.Column('photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_changes', 'photo_path')
    # ### end Alembic commands ###
