"""care tracking tables

Revision ID: 9271af81a100
Revises: f108fc2db179
Create Date: 2026-06-22 12:59:09.223484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9271af81a100'
down_revision: Union[str, Sequence[str], None] = 'f108fc2db179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bp_targets',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('sys_low', sa.Integer(), nullable=False),
    sa.Column('sys_high', sa.Integer(), nullable=False),
    sa.Column('dia_low', sa.Integer(), nullable=False),
    sa.Column('dia_high', sa.Integer(), nullable=False),
    sa.Column('doctor_label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('prescriber', sa.String(), nullable=True),
    sa.Column('prn', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('pack_pickup', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_person_id'), 'medications', ['person_id'], unique=False)
    op.create_table('bp_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bp_readings_person_id'), 'bp_readings', ['person_id'], unique=False)
    op.create_index(op.f('ix_bp_readings_taken_at'), 'bp_readings', ['taken_at'], unique=False)
    op.create_table('medication_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_changes_person_id'), 'medication_changes', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_changes_person_id'), table_name='medication_changes')
    op.drop_table('medication_changes')
    op.drop_index(op.f('ix_bp_readings_taken_at'), table_name='bp_readings')
    op.drop_index(op.f('ix_bp_readings_person_id'), table_name='bp_readings')
    op.drop_table('bp_readings')
    op.drop_index(op.f('ix_medications_person_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_table('bp_targets')
    # ### end Alembic commands ###
